# config/default.toml

base_url = "wss://stream-testnet.bybit.com/v5/"
endpoints = [
#    "public/spot",
#    "public/linear",
#    "public/inverse", moet veder nakijke welke combi's er zijn
#    "public/option",  response heeft geen req_id
    "private"
]

#trading_pairs = ["BTCUSDT", "APTUSDT", "MNTUSDT", "ETHUSDT", "XRPUSDT", "SANDUSDT", "SANDUSDT"]
#public_topics = ["orderbook.1", "orderbook.50"]
#private_topics = ["position", "execution", "order", "wallet", "greeks"]
trading_pairs = ["BTCUSDT", "APTUSDT", "ETHUSDT", "XRPUSDT", "MNTUSDT", "SANDUSDT", "SOLUSDT", "ADAUSDT", "DOTUSDT", "MANAUSDT"]




api_key = "zxeksSms3ZzdcNtsLx"
api_secret = "ZlBUmr1XDy3cAlUZ64A0bd6s5pEUhteoNoYu"
recv_window = "1000"
private_key = """
-----BEGIN PRIVATE KEY-----
MIIJQQIBADANBgkqhkiG9w0BAQEFAASCCSswggknAgEAAoICAQCsL2zkoEo08yYE
w2xpKqbNbfWRJZvlvV6piecxLcWl9dtSPbfI2v8cBe99IbLR/fkuh+dHySn5rsoN
ddeVY/ftC5f+wKqFCSilb445JoY9XKUkpoqoKQZU0iYuW8AEoMqlY7iT36CbNnxV
l79LGYm+PRPVm1mGqzdfFaSbKVI1smdT/QL/a8UlxyBKtj2Jo22zHwHIJaDenRRQ
OFJn2SN5ixzcW41em0suF5fDwemGV0NzDm3JToOrGFUIY6g+vdS9vSMcCoqmVZBt
WJB3qiZpqlZvxA4W/Towe8gjtbWdiRjm38j1lIbrYrKsKwWu5L/9oXzHJ9VkEGgo
VIzftKvnDFWmbCHJgcQlLPg4Qd1z1VKxcFp9tOX++bW0k2YhgEQtLITrFMAw+f58
EzXs3ZJPWfqf3JIocfrARKpEozPV6+oWaZR8RwP5QtJqw6qTR/AOQvgvTbbDqjcR
S0OlpMq+FCcmQ2jW70pOxL1ltyIohXrZY/T/Wo/BkUXFAQSdiUtn4HKm7Gjq5EuI
HIr8AnlZoA1V2wGu33D7O+p/VN+Z2QaA+qY9el6bY3V0BtJAOH+KYJhIIG0eyJ/v
giANfUGkz1e2UYVX021XHkdpK9JPlsfkUj9iktn3jxZghFz6d7Ijdwlk6vOl/H2j
JGgCgP6QDBBdDQARF7RJFgTq65hX1QIDAQABAoICAAv4JQH0mYv6PhGVMydRYXSE
2Q38twxeoGK5NSLQS33IrDUYmLrD7Hl6eSYx7kAWP1jqdhuhooMakS2j3DdkkmK+
TFPXeVMTqqlrao/S+4Bu/QTh9eAQMAI79I8C7kN0GPorxzQyVrQLctOxX4kdLpvU
m5kc+jl4E/qOYtmtYutcKj4mp6txRqxkXfyLlBYKEBFkTaen4/mtojCcZbAV4lcr
4jb4P0jNE0oSNkjTpUPjM4tfPKcCh/kgESMq6FJqOExzRipIGlDLQGW1gx9qas6s
GmOdFZyoAEBIDoba9hPMKLi95DacG0/oFcMNn5DDkowTSnz+qiERWeg5zmwrn0ps
W6o6wiXyiHmK0tE6UEvJM1XN/++wFTW7b/u22nFnMUNjXWZzJup3tb84qQaPffym
0F6pXdBwV2JLYebLz6hT6QW39hyQQ+rqVhQMA7Dw+YAAkSkjtutCXVqcK3KXvkMT
ucUlN8R+1be6BaRVXNw4ab5gFC1mpuMHW0reMkryQWgQt3dK7PmF7le5GnPbjWJ5
FQeLW2LjDFnsQb/G4q+iB9ugEzsivdPjDKp3t1+qxcBqPkxXBg3glGMzYdKFDadZ
58xTeG/KSSyqyUAHarCkTwWzi9z1pzv+hL+ME2DNaI//seOjx5U0pXdwPksdqAqT
od/nV8tBixs8IPqTTLl5AoIBAQDmAryvdrJrY9Ge0DFnmqnLoZecSpoJBcDOtp2a
DM1zn6xM6ugZXwJ0OpW+cUrSoHTUkGYyQrr2GDudhHmlJ7f3wtmKbJrBrR5Ok0fL
VS8IBaG7HV5lSW6ezEzCyppPuUT70sfMlOccBLnUzJ+l35J009jpJLcH37wQtwyU
Bi8Z2PKr/EAUT04A4beMnU79VIoN25YAvYHzamV8atbDjAYhjbHByros9m5r71cn
03nTu8i8bTE1dH1D4Y+E1/d6jdIU25mBzRxmyQEnIsO3PDrUJqxV9lubcLM2b8HM
zJrO6gfMhCQhs4FJiVGjz+kVBeCpX2tC0pfzGrvoBIuE7KA9AoIBAQC/pAlOu++6
b3AgZ+MM6tP0wNINKx5D6T57l8HAvW9vi+aIbjSudZZGeuxc7iWhjXilBat00O9L
X1QhLFRQwGdPPG3jAB+JVHwruSbQZS8qlG+zqXBrAGsKyuac1uZDMW2+qyp499T8
zOBZNf9JEAlCQi0JV+7RTT0TwBZPdJ/wPCvzZ1PX0W+okrNGWSWKBqXgwGpnZfKY
/NK2CNniHqDeHnTzxs7efAvutnOcdTjEBBKPIE9U0O+0A9PUXzqVv8FjwcrlOglm
faZWVpkVaVzJDfqpTI2Pp4xfA949H8xj4gg8ryA9tiYee8e7664KUE33NhdUDKau
qLU3xFjsWbd5AoIBAHJIu93m+UHYqAfj5BhZRbKTCNS0UJLZE/Lh067+W3ruxFq3
gTlR9tMvZMXqXsYGyeXwFYc1ltW+NqjOcO65rHPjkdlwmvhOfzeFgG+sVKEEw1ZI
gmWLNfabBiznJAMmx/rjwTiKZ8aJJphwT4bIbmmz9RvqjTLRXQ1lFk/aPr72B6Wi
wWgV+2j+vgeVBfFjdvDpwT9+6bm7jM9j+m/Q/B7h24expg2/KCBjHIgCUI7+x/+v
tXqc9byrr3bPI/z1yINqlXxkII+FohgC8wHxYD2XNZvEu8GhHrqWjtGme+kBaXyZ
z6YbHcse+ryNCn/Sms0tRws9vhghmWnwEC6sr/UCggEAS9XP0RZRwUcD6e7yTFRI
19vNw2RCr8EG9sWQ6IKOLGgCLA7gTgE+HFncWtHqlklzamoZ9ToQ15S7p/zwyJu6
xgI1wdR0plWGZY75KxI/XewrX783O0CJG1Y7d+kaaZCPyxnUztXTtM4mIWdaxEDS
SSQCymW/nZehCcXDjmGqQNiu070Z0peQRfb3dmkkj8AduBisgoo3PA8gGuTZw783
DW6j/Su5BRW1axtMGKfSdM7fwT+Z5QhhMq0pECs29bdSAfXYImma+rHSNuxB29U7
4Fvly0T959D3nUnckfeZXBVACTOL4J/J6do1qcmTr4UjtSX0iVAQTaF5RL4wKic+
kQKCAQAW/wwovKL2XOf15Nz3gsd4q1N/4bhaQGlK0TSX+iCVXPhqJTVhKn5+Tzt/
ZqhKB+SxZ7LmuAs9mr8EvgdRF70WQlSvQaoQkwNNlu9S7tKxxbNMw9OW7toYFlzf
kp6+yeLVIrTeAPO9vEUVY6gfxPKVqt4KpyJBHCGuEsW7R9MyPph7HWeW9iE45E9X
v/kkPaazl+o1Yflm7ZsVcJw4SNkBDihdQU98maV0cqtwuvEjQ4oPYQwQDjsU5Yz+
1kHKwnG/2RBQer8jLU70UcFEw4+DTGPytotB7r19o+ANT6MPUfwsCGKW30JbNtBw
F5qm7raXEluLpLm8KG1xMnP5A4Mx
-----END PRIVATE KEY-----
"""


[topics]
#spot kent geen orderbook level 500 en ook geen liquidation
spot = ["orderbook.1", "orderbook.50","orderbook.200","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60"]
linear = ["orderbook.1", "orderbook.50","orderbook.200","orderbook.500","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60", "liquidation"]
inverse = ["orderbook.1", "orderbook.50","orderbook.200","orderbook.500","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60", "liquidation"]
option = ["orderbook.1", "orderbook.50","orderbook.200","orderbook.500","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60", "liquidation"]
private = ["position", "execution", "order", "wallet", "greeks"]