# config/default.toml

base_url = "wss://stream-testnet.bybit.com/v5/"
endpoints = [
    "public/spot",
    "public/linear",
#    "public/inverse", moet veder nakijke welke combi's er zijn
#    "public/option",  response heeft geen req_id
#    "private"
]

#trading_pairs = ["BTCUSDT", "APTUSDT", "MNTUSDT", "ETHUSDT", "XRPUSDT", "SANDUSDT", "SANDUSDT"]
#public_topics = ["orderbook.1", "orderbook.50"]
#private_topics = ["position", "execution", "order", "wallet", "greeks"]
trading_pairs = ["BTCUSDT", "APTUSDT", "ETHUSDT", "XRPUSDT", "MNTUSDT", "SANDUSDT", "SOLUSDT", "ADAUSDT", "DOTUSDT", "MANAUSDT"]

[topics]
#spot kent geen orderbook level 500 en ook geen liquidation
spot = ["orderbook.1", "orderbook.50","orderbook.200","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60"]
linear = ["orderbook.1", "orderbook.50","orderbook.200","orderbook.500","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60", "liquidation"]
inverse = ["orderbook.1", "orderbook.50","orderbook.200","orderbook.500","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60", "liquidation"]
option = ["orderbook.1", "orderbook.50","orderbook.200","orderbook.500","publicTrade", "tickers", "kline.1", "kline.3", "kline.5", "kline.15", "kline.30", "kline.60", "liquidation"]
private = ["position", "execution", "order", "wallet", "greeks"]